server:
  port: 8080


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
    config:
      enabled: true
    main:
      web-application-type: reactive

jwt:
  secret: tvr+7OoVISnTvYGNHp9wIglARX4FCUoC3DPRTS0mToY=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#zuul:
#  routes:
#    customer-service:
#      path: /customer-service/**
#      service-id: customer-service
#      accounts-service:
#        path: /accounts-service/**
#        service-id: accounts-service
#      credits-service:
#        path: /credits-service/**
#        service-id: credits-service
#      transactions-service:
#        path: /transactions-service/**
#        service-id: transactions-service
#      reports-service:
#        path: /reports-service/**
#        service-id: reports-service
#      cards-service:
#        path: /cards-service/**
#        service-id: cards-service
#      auth-service:
#        path: /auth-service/**
#        service-id: auth-service

