server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts-service/**
        - id: credits-service
          uri: lb://credits-service
          predicates:
            - Path=/credits-service/**
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions-service/**
        - id: reports-service
          uri: lb://reports-service
          predicates:
            - Path=/reports-service/**
        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/cards-service/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
    config:
      enabled: true
    main:
      web-application-type: reactive

jwt:
  secret: tvr+7OoVISnTvYGNHp9wIglARX4FCUoC3DPRTS0mToY=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka