spring:
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000

kafka:
  bootstrap-servers: localhost:9092

redis:
  host: localhost
  port: 6379
  timeout: 2000