server:
  port: 8087

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/authdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: tvr+7OoVISnTvYGNHp9wIglARX4FCUoC3DPRTS0mToY=

logging:
  level:
    root: INFO
    com.example.auth: DEBUG
    org.springframework.data.mongodb.core: DEBUG
