server:
  port: 8088

spring:
  application:
    name: bootcoin-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bootcoindb
  kafka:
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.example.bootcoin: DEBUG
    org.springframework.data.mongodb.core: DEBUG

springdoc:
  paths-to-match: /**
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs