server:
  port: 8083

spring:
  application:
    name: credits-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditsdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.example.credits: DEBUG
    org.springframework.data.mongodb.core: DEBUG

springdoc:
  paths-to-match: /**
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs