server:
  port: 8081

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customersdb
  cloud:
    config:
      uri: http://localhost:8888
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

customer-service:
  cards-service-url: http://localhost:8086/api/cards
  accounts-service-url: http://localhost:8082/api/accounts

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.example.customer: DEBUG
    org.springframework.data.mongodb.core: DEBUG

validation:
  vip:
    min-credit-limit: 10000
  pyme:
    min-credit-limit: 5000

springdoc:
  paths-to-match: /**
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
