server:
  port: 8081

spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customersdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.example.customer: DEBUG
    org.springframework.data.mongodb.core: DEBUG

validation:
  vip:
    min-credit-limit: 10000
  pyme:
    min-credit-limit: 5000

springdoc:
  paths-to-match: /**
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
