server:
  port: 0

spring:
  application:
    name: reports-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reportsdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.banco.reports: DEBUG
