server:
  port: 8085

spring:
  application:
    name: reports-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reportsdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    com.example.reports: DEBUG

springdoc:
  paths-to-match: /**
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
